# Generated by Django 4.2.4 on 2023-08-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('choice1', models.TextField(null=True)),
                ('choice2', models.TextField(null=True)),
                ('choice3', models.TextField(null=True)),
                ('choice4', models.TextField(null=True)),
                ('survey_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
