# Generated by Django 4.2.4 on 2023-08-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='readingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('report', models.TextField(verbose_name='후기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='추천인', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='good_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
