# Generated by Django 4.2.4 on 2023-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='img',
            field=models.ImageField(default=1, upload_to='reading_list_images/'),
            preserve_default=False,
        ),
    ]
